name: flake8 Linter

on: [push, pull_request]

jobs:
  flake8-linter:
    runs-on: ubuntu-latest
    name: flake8-linter
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Runs flake8 Lint
        uses: py-actions/flake8@v1
